as yet unclassified
initializeRequiredPrefixes
        self setPrefix: 'owl' URI: 'http://www.w3.org/2002/07/owl#'.
        self setPrefix: 'rdf' URI: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#'.
        self setPrefix: 'rdfs' URI: 'http://www.w3.org/2000/01/rdf-schema#'.
        self setPrefix: 'rdfa' URI: 'http://www.w3.org/ns/rdfa#'.
        self setPrefix: 'xhv' URI: 'http://www.w3.org/1999/xhtml/vocab#'.
        self setPrefix: 'xml' URI: 'http://www.w3.org/XML/1998/namespace'.
        self setPrefix: 'xsd' URI: 'http://www.w3.org/2001/XMLSchema#'.
        ^ self
